<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.5" />   
    <xacro:property name="base_width" value="0.3" />
    <xacro:property name="base_height" value="0.08" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
        
    <!-- base_footprint (projection of base_link on the ground) -->

    <link name="base_footprint"/>
    
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.14" rpy="0 0 0"/>
    </joint>
    
    <!-- base_link and base_scan (required for Nav2) -->

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="10.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>
    
    
    
    <!-- Wheels (4 differential wheels) -->
    

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi /2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi /2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="0.5" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi /2.0} 0 0" />
        </link>
    </xacro:macro>

    <joint name="base_fl_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="fl_wheel"/>
        <origin xyz="0.225 ${(base_width + wheel_length) / 2.0} -0.05" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

   
    <xacro:wheel_link prefix="fl" />
     
    
    <joint name="base_fr_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="fr_wheel"/>
        <origin xyz="0.225 ${-(base_width + wheel_length) / 2.0} -0.05" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="fr" />
   
    <joint name="base_rl_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rl_wheel"/>
        <origin xyz="-0.225 ${(base_width + wheel_length) / 2.0} -0.05" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="rl" />
    
    <joint name="base_rr_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rr_wheel"/>
        <origin xyz="-0.225  ${-(base_width + wheel_length) / 2.0} -0.05" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:wheel_link prefix="rr" />


</robot>